spring:
  application.name: text-to-image-demo
  ai:
    stabilityai:
      api-key: ${STABILITYAI_API_KEY}
      image:
        options:
          model: stable-diffusion-xl-beta-v2-2-2
logging:
  level:
    root: info
    com.dardeus: trace
